# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelist',
            name='collaborators',
            field=models.ManyToManyField(null=True, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placelist',
            name='followers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placelist',
            name='list_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='placelist',
            name='places',
            field=models.ManyToManyField(null=True, to='api.Place'),
        ),
    ]
