# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170219_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placelist',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placelist',
            name='places',
            field=models.ManyToManyField(blank=True, to='api.Place'),
        ),
    ]
